### ISSUE TITLE
How can I use it?

### ISSUE THREAD

**Issue by aloisdg** [nunit/nunit-vs-testgenerator#1]
Hello,

Can you share a screenshot of the extension?
Can you share a usecase of the extension?

Thank you!

**Comment by rprouse** [comment]
Sorry, we've been meaning to write some documentation, but keep
procrastinating.  I will try to write up something today, if only a blog
post and add the link here.

**Comment by aloisdg** [comment]
I would be perfect. Thank you.

**Comment by rprouse** [comment]
@aloisdg I tried to document this extension, but unfortunately this only works for Visual Studio 2015 Enterprise edition which I do not have. If you do and would like to use it, Microsoft has decent documentation at https://msdn.microsoft.com/en-us/library/dn823749.aspx

**Comment by rprouse** [comment]
@aloisdg, I have updated the README here on GitHub and the page in the [Visual Studio Gallery](https://visualstudiogallery.msdn.microsoft.com/bd30bf3f-4183-4b00-a245-1875316b8cd3) with more information. Thanks for letting us know that our documentation was lacking :+1:

**Comment by aloisdg** [comment]
That seems awesome! As a Community user I can use it but still.

**Comment by rprouse** [comment]
@aloisdg, I made a mistake. I think there was a problem with my install of the test extension. I re-installed and the Create Unit Test is now working. It is only the IntelliTests portion that requires Visual Studio Enterprise. You should be able to create unit tests using this extension from Community Edition.

For information on how to use it, check out the README here on GitHub, or the page in the Visual Studio Gallery.

**Comment by aloisdg** [comment]
@rprouse Nice information!
