### ISSUE TITLE
Does not show in context menu for Creating a Unit Test in VS 2015 Pro w/Update 3

### ISSUE THREAD

**Issue by ravensorb** [nunit/nunit-vs-testgenerator#18]
I have tried adding/removing this added multiple times and cannot seem to get the "Create Unit Test" to show up in the context menu when I write click on "white space" within a specific method.

Right Click Context
![Right Click](https://i.imgur.com/I93sbac.png)

Visual Studio About
![VSAbout](https://i.imgur.com/Lo8F6hT.png)

**Comment by rprouse** [comment]
This NUnit extension does not create the menu item, that is the responsibility of Visual Studio. The NUnit extension doesn't get called until after you see the generate test dialog and you pick NUnit as the test framework.

I am closing this as a bug in Visual Studio, not the adapter. @OsirisTerje please reopen if you think I have misdiagnosed.

**Comment by ChrisMaddock** [comment]
Seems to work for me in VS 2015/3. 

@ravensorb - Are you by any chance using dotnet core? The extension isn't compatible with dotnet core - see #12

**Comment by ravensorb** [comment]
Good question.  Its a PCL project set for .NET Standard 1.3 that I am trying to use it in.
