### ISSUE TITLE
Cannot generate unit test in the same project as production assembly

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-vs-testgenerator#19]
@vnvizitiu commented on [Fri Nov 11 2016](https://github.com/nunit/docs/issues/143)

When trying to generate unit tests in the same project, a error message box shows up and lets me know that it cannot add a reference as it will create a "self-reference"

I know it is a bad practice to have unit tests in production assemblies, but that is coding model the group i work with has adopted and won't change it, though the create dialog box does allow me to choose that project and even finds the test file i have setup

---

@CharliePoole commented on [Fri Nov 11 2016](https://github.com/nunit/docs/issues/143#issuecomment-260051863)

@vnvizitiu Is this intended to be an issue against the nunit-vs-testgenerator project? If so I can move it.

---

@vnvizitiu commented on [Fri Nov 11 2016](https://github.com/nunit/docs/issues/143#issuecomment-260052076)

ouch, yeah, my bad, saw that there were other generator related issues in the backlog, please move it then

**Comment by rprouse** [comment]
This may be a Visual Studio bug. AFAIK, We don't have any UI or try to add references, I believe that is all Visual Studio. Our test generation code gets called later in the pricess. 

I am adding the confirm label so we can check if it our bug.

**Comment by OsirisTerje** [comment]
This is nothing the extension can control.  I'll forward this to the MS Product Group, so they can answer - but I would assume this is by design.

**Comment by pvlakshm** [comment]
The Create Unit Tests wizard asks the extension to give the information based on referenced assemblies that it understands.
For e.g. if you were dealing with MSTest V2, and the product assembly had the references to MSTest V2, then they would show up in the drop down (same would be the case with NUnit/xUnit.net as well).
