### ISSUE TITLE
Review and (if necessary) correct copyrights on testgenerator.

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-vs-testgenerator#22]
The license file indicates it is copyright to both Microsoft and to "nunit.org". In addition there is a notices file that says it is based on a commit provided by Microsoft. Having the notices file and the copyright is contradictory and I would say that assigning copyright to our work to Microsoft is incorrect and probably not expected by Microsoft. 

The use of a notices file to acknowledge the original source is required by some licenses (e.g. Apache 2) but not by the MIT license. It is, however, a nice thing to do and it is what I did for the original NUnit team in NUnit itself, which has a notices file. Note that the old team there is only isted in the notices file because it is a courtesy. They don't hold a copyright to the NUnit 3 software. Neither does Microsoft hold a copyright to the current testgenerator as far as I understand, not being a lawyer.

Beyond that, there is no legal entity known as "nunit.org" so it seems like an odd usage. I suppose people kind of know what we mean, but it could lead to problems. Such vagueness has, in fact, led to problems for other projects when people have split up and gone their own ways. I admit this is but a small problem for such a small program, but I'd rather we did it the right way. Copyright is the heart of Open Source and I think you have to learn a bit about it and handle it well.

While I could hold the copyright as I do for other NUnit software, this one is a late edition, with which I had little to do. In fact, I even argued against our doing it. I would find it perfectly reasonable for Terje to hold copyright, since he originated it.. A second alternative would be to assign it fully to Microsoft in a formal way and to have it maintained elsewhere. A third would be for it to be temporarily held by NUnit Software, as some of our programs are. That's actually an existing legal entity in the State of Washington.

These are all just ideas. Mainly I'm concerned that we ought to clean this up one way or another.

**Comment by OsirisTerje** [comment]
I see your point.  Imho I feel it is best if it is copyrighted by an organization, so if NUnit Software is a legal entity, then I think it might be wise to use that.  You say temporarily, over time - I think there should be a legal NUnit entity to hold it over a long time, it makes more sense, even if people within changes, the copyright would be the same. 

Credits however, would be nice to add somewhere, so that people involved are being credited, but without holding anything legal.

**Comment by CharliePoole** [comment]
Stuff is under way to eventually designate a permanent copyright holder for the things I hold currently. While I'm not too keen on increasing the number of things I'm responsible for re-housing, I guess it's no harm to add this little thing. Honestly, however, both credit and copyright could easily be yours as far as I'm concerned and you could add other people who make a significant contribution if and when you wanted. That's actually how the original NUnit project did it.

Mainly, I'd just like to get Microsoft off it.
