### ISSUE TITLE
Create Unit only works in classes 

### ISSUE THREAD

**Issue by JackGrinningCat** [nunit/nunit-vs-testgenerator#27]
Hi,

I just created a small struct and added some static functions. 
I wanted to create a unit test but it pop (is it written like that 💩 ) up a message box
"Value cannot be null.
Parameter name codeClass"

Is this a wanted limitation of this extension, that it has to be a class?

Chris

**Comment by OsirisTerje** [comment]
Yes :-)

Microsoft.....

**Comment by JackGrinningCat** [comment]
@OsirisTerje That means that is a limitation by Microsoft? 
Do you know a place where I can file then this issue?

**Comment by OsirisTerje** [comment]
I would go to https://developercommunity.visualstudio.com/spaces/8/index.html  .  That is the best place.  The main parts here are not open source, only the extensions for the different frameworks
