### ISSUE TITLE
No Create Test Unit menu item for  Shared Projects in VS2019 

### ISSUE THREAD

**Issue by chostelet** [nunit/nunit-vs-testgenerator#32]
The subject tells the issue.

Using VS2019 Professional version 16.0.2 and Test Generator NUnit extension version 2.2 installed from within VS (Extensions -> Online, etc...).
Using too NUnit 3 test Adapter version 3.13.0.0 and NUnit VS Templates version 1.5.3.

Note: for creating tests I had to use NuGet to install NUnit v3.11.0.

However tests ("made by hands") are visible in the Test Explorer.

**Comment by OsirisTerje** [comment]
The Create Test Unit menu item comes from Visual Studio itself. 
![image](https://user-images.githubusercontent.com/203432/57199337-090e3800-6f7e-11e9-8579-3f3ca9a2daae.png)

If you do the same, do you then see the menu item ?

**Comment by chostelet** [comment]
Yes... and No!

I can see this “Create Unit Tests” in a simple project.
However, I cannot see it when I click on a method which is contained in a *shared project*.
In that case I only see “Run Test(s)” and “Debug Test(s)”.

Could it be the explanation?

**Comment by OsirisTerje** [comment]
I assume you mean the VS Shared Project feature ?  
It would be awesome if you could make a very simple repro sln, zip it up here or add it to a github repo, so I could have a direct look.  If there are cases where this doesn't show up where it should, it is interesting.  :-)

UPDATE:

I  made a repro project, and can confirm it doesn't work for classes in a Visual Studio Shared Project.
![image](https://user-images.githubusercontent.com/203432/57212960-a0f33c80-6fe5-11e9-8bde-dcf86b4699f6.png)

This might be a bug in Visual Studio, so I will post this forward, and mark it is a VS Issue.

**Comment by chostelet** [comment]
OK, glad to see it is confirmed.
Thanks for taking care of this issue.

**Comment by OsirisTerje** [comment]
This https://developercommunity.visualstudio.com/content/problem/101849/create-unit-tests-does-not-work-with-c-shared-proj.html
is the MS tracking issue.

Please upvote it .  :-)

**Comment by chostelet** [comment]
Done :)

 

--

Christian HOSTELET - Grenoble

 

De : Terje Sandstrom <notifications@github.com> 
Envoyé : lundi 6 mai 2019 21:37
À : nunit/nunit-vs-testgenerator <nunit-vs-testgenerator@noreply.github.com>
Cc : Christian Hostelet <christian.hostelet@free.fr>; Author <author@noreply.github.com>
Objet : Re: [nunit/nunit-vs-testgenerator] No Create Test Unit menu item for Shared Projects in VS2019 (#32)

 

This https://developercommunity.visualstudio.com/content/problem/101849/create-unit-tests-does-not-work-with-c-shared-proj.html
is the MS tracking issue.

Please upvote it . :-)
