### ISSUE TITLE
Does not work with partial classes 

### ISSUE THREAD

**Issue by mccabesp** [nunit/nunit-vs-testgenerator#37]
I have a MVC controller class wilth multipl MVC action in methods spread across multiple partial files. 

1. When creating unit tests from the first partial it work OK but only invludes methods in that partial and not for the entire class.
2. When I create from a second partial class it throws an error saying "Test file already exists"

**Comment by OsirisTerje** [comment]
Just tried it, and could not repro the failure  (2)
(1) though I can repro.  

This is however something that is outside the extension.  I'll try to figure out the best way to report this back to MS. 

@AbhitejJohn Any suggestions ?

**Comment by AbhitejJohn** [comment]
(1) is expected to happen, given the context of where the action was initiated. 
I'm not able to repro (2) as well. One thing that might be a problem is that the file name is drawn from the class name, so if you choose to output to a new file, please ensure that the file name format is updated accordingly (below is just an example):
![image](https://user-images.githubusercontent.com/18014426/87362896-d918d800-c524-11ea-8fe9-52645b6a9013.png)
