### ISSUE TITLE
Feature Request: Auto Mock Support

### ISSUE THREAD

**Issue by CoenraadS** [nunit/nunit-vs-testgenerator#40]
Hello

Since NUnit is very often used with moq, the developer has to write a lot of `[SetUp]` boiler plate to add Mocks for each field in the constructor of the Sut,

It would be great if this extension could support doing this.

i.e. If class only has 1 constructor, auto generate [SetUp] and Mock<T> for each reference type in the constructor.

**Comment by rprouse** [comment]
Our policy is to not take a dependency on other projects. I think we would need to take a dependency on Moq to do this?

I think this would likely be better served by a separate package/project.

**Comment by mattwhitfield** [comment]
FWIW, I wrote an extension called UnitVerse that does do automatic mocking.

**Comment by OsirisTerje** [comment]
@mattwhitfield Can you add a link to that?   

About Moq, NSubstitute is also big in this space, so IMHO any tools should cover both.

**Comment by mattwhitfield** [comment]
@OsirisTerje - https://marketplace.visualstudio.com/items?itemName=MattWhitfield.Unitverse for VS2019 and https://marketplace.visualstudio.com/items?itemName=MattWhitfield.UnitverseVS2022 for VS2022. It supports multiple mocking and test frameworks...
