### ISSUE TITLE
Add Support for VS2022

### ISSUE THREAD

**Issue by iodar** [nunit/nunit-vs-testgenerator#41]
Hello everyone,

First of all thank you for developing this extension which makes work a lot easier.

I wanted to ask whether it is planned that this extension will support _Visual Studio 2022_.

Thanks in advance.

Best regards,
Dario

**Comment by iodar** [comment]
Hallo all, I wanted to ask whether there are any news on the topic above?

**Comment by mattwhitfield** [comment]
@iodar - FWIW, I found https://cezarypiatek.github.io/post/migrate-vsix-to-vs2022/ pretty helpful when I was adding VS2022 support to my test generator extension. Following that approach you end up with a version for VS2022 and above which was separate. The RandomEngy extension seems to support VS2022 ok from one extension, so no idea what they did there.

Just thought that might be helpful if you wanted to have a crack at adding VS2022 support.

**Comment by marbel82** [comment]
I found another extension:

https://github.com/RandomEngy/UnitTestBoilerplateGenerator

but it can only generate tests for whole class. I can't generate test for a single method.

**Comment by mattwhitfield** [comment]
@marbel82 - Mine (https://github.com/mattwhitfield/Unitverse) does allow you to generate for single methods, if that helps.

**Comment by marbel82** [comment]
@mattwhitfield  Looks promising. Only one thing is missing, I need to select the project to which the test will be added.

Some methods I test in project App_UnitTests and some in App.IntegrationTests. Also project names evolved over years, so we have many patterns.

**Comment by rprouse** [comment]
We'd like to add support, it is just a matter of resources. If anyone wants to make the necessary updates, I'd be glad to review the PR and get it released.

**Comment by iodar** [comment]
> We'd like to add support, it is just a matter of resources. If anyone wants to make the necessary updates, I'd be glad to review the PR and get it released.

Thank you for clarifying that. I am looking forward to the release.

**Comment by Mudoch** [comment]
I'd like to add my voice to encouraging the update to VS2022. Thank you.

**Comment by efhilton** [comment]
@rprouse I see a PR that seems to add support for VS2022.  Any chance this is the magical one that gets us Nunit test generation on vs2022? Pretty please? ;)

**Comment by willjblair** [comment]
#43 - linking pull request for reference

**Comment by rprouse** [comment]
The PR for this requires a lot of work so I moved it over to #46 and am adding to it and following https://learn.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

**Comment by iodar** [comment]
> I found another extension:
> 
> https://github.com/RandomEngy/UnitTestBoilerplateGenerator
> 
> but it can only generate tests for whole class. I can't generate test for a single method.

This is really good. Have been using it a bit and I can say it works well. Only disadvantage is adding new test methods. Has no support for that as far as I can see. But still really useful. Thanks @marbel82 for the suggestion.
