### ISSUE TITLE
Not compatible with net6.0

### ISSUE THREAD

**Issue by SurajitMU** [nunit/nunit-vs-testgenerator#42]
I am trying to run NUnit tests in VS Code but it seems the version of NUnit extension in VS Code is not compatible with net6.0.

My .csproj file configuration:
```csproj
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
    <PackageReference Include="NUnit.Analyzers" Version="3.3.0" />
    <PackageReference Include="coverlet.collector" Version="3.1.2" />
  </ItemGroup>
```
I getting following errors when I run 'dotnet test' from the terminal: 

 error NU1100: Unable to resolve 'Microsoft.NET.Test.Sdk (>= 17.1.0)' for 'net6.0'.
 error NU1100: Unable to resolve 'NUnit (>= 3.13.3)' for 'net6.0'.
 error NU1100: Unable to resolve 'NUnit3TestAdapter (>= 4.2.1)' for 'net6.0'.
 error NU1100: Unable to resolve 'NUnit.Analyzers (>= 3.3.0)' for 'net6.0'.
 error NU1100: Unable to resolve 'coverlet.collector (>= 3.1.2)' for 'net6.0'.

Please let me know if anyone has faced this issue as well.

**Comment by OsirisTerje** [comment]
This is not an issue for the Test Generator extension.
