### ISSUE TITLE
Visual Studio 15 support

### ISSUE THREAD

**Issue by xperiandri** [nunit/nunit-vs-testgenerator#8]

**Comment by CharliePoole** [comment]
Sorry... you have to tell us what your issue is.

**Comment by rprouse** [comment]
@xperiandri, Same as your other issue, I assume that you mean that the test adapter does not work in Visual Studio '15'. Do you get errors or does it just not install? A bit more info and we can reopen this issue.

**Comment by rprouse** [comment]
Reopening. I checked the VSIX manifest and it is locked at 14.0.

`<InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[14.0]" />`

**Comment by rprouse** [comment]
Marked as easyfix assuming that it is just allowing it to be installed on 15.0. If not, then we may need to remove the label :smile:

**Comment by OsirisTerje** [comment]
It crashes in VS15 due to the references to the VS dll's.  Seems there are incompatible changes, at least in the Pex parts.  We may need to split this into a VS2015 versions and vNext (V15) version

**Comment by ghost** [comment]
Is this working for VS2017 anywhere?

**Comment by OsirisTerje** [comment]
We are in the process of releasing it with support for VS 2017.  I will have to be a separate VSIX.

**Comment by OsirisTerje** [comment]
Released now:  https://marketplace.visualstudio.com/items?itemName=NUnitDevelopers.TestGeneratorNUnitextension-18371
