### ISSUE TITLE
Not Able to Generate NUnit Tests

### ISSUE THREAD

**Issue by lpeteet** [nunit/nunit-vs-testgenerator#9]
I am using VS2015, VB.NET and the NUnit Test Adapter as Well as Test Generator NUnit Extension.  When I Right-Click on an item in my Solution it does not provide the ability to Create NUnit Tests (or any other tests for that matter).

Can anyone help?

Thanks!!

**Comment by rprouse** [comment]
You need the Ultimate edition of Visual Studio to generate IntelliTests, but it does work with all other versions to generate tests for methods.

In the editor window, right click in the method or class you would like to test and click Create Unit Tests in the context menu.

**Comment by lpeteet** [comment]
Thanks!!  I have VS2015 Professional and it doesn't show any options for
creating test links.  It was there before but since I have tried NUnit 3.2
and that didn't work so went back to NUnit 2.6.4 so I could use the Runner
GUI it now doesn't show any options.  I also removed the reference to
Microsoft MSUnit as I didn't want to end up using that by mistake.

I am pretty new to Unit Testing Frameworks but have used them some in the
past with Visual Studio.

Regards

On Tue, Apr 26, 2016 at 4:20 PM Rob Prouse notifications@github.com wrote:

> You need the Ultimate edition of Visual Studio to generate IntelliTests,
> but it does work with all other versions to generate tests for methods.
> 
> In the editor window, right click in the method or class you would like to
> test and click Create Unit Tests in the context menu.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/nunit/nunit-vs-testgenerator/issues/9#issuecomment-214873772
> 
> ## 

_Larry S. Peteet_

_Senior Software Engineer_
_Research & Development_
_PETEET LLC__Phone:_ | _Cell:_ 425.577.8334
LarrypV10@GMail.com

http://www.linkedin.com/pub/larry-peteet/0/736/b21

**Comment by rprouse** [comment]
If you want to run NUnit 3 tests in a GUI, you can use the NUnit 3 Test Adapter extension. Install from Tools | Extensions. Adding the Microsoft test framework reference to your project will definately cause it to not show up properly, so good thing you removed it.

**Comment by lpeteet** [comment]
Thanks again!  I tried NUnit 3 but from what I read there was no GUI for it
with VB.NET in VS2015.  I added the extension but could not get this to
work.

Kindly,

LarryP

On Tue, Apr 26, 2016 at 9:19 PM Rob Prouse notifications@github.com wrote:

> If you want to run NUnit 3 tests in a GUI, you can use the NUnit 3 Test
> Adapter extension. Install from Tools | Extensions. Adding the Microsoft
> test framework reference to your project will definately cause it to not
> show up properly, so good thing you removed it.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/nunit/nunit-vs-testgenerator/issues/9#issuecomment-214936972
> 
> ## 

_Larry S. Peteet_

_Senior Software Engineer_
_Research & Development_
_PETEET LLC__Phone:_ | _Cell:_ 425.577.8334
LarrypV10@GMail.com

http://www.linkedin.com/pub/larry-peteet/0/736/b21
